  name: run-uvicorn
  
  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Run server
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.HOST_DNS}}
            username: ${{secrets.USERNAME}}
            key: ${{secrets.EC2_SSH_KEY}}
            script: |
              cd ${{secrets.TARGET_DIR}}/backend
              python3 -m pip install -r reqs.txt
              cd ${{secrets.TARGET_DIR}}
              ~/.local/bin/uvicorn backend.main:app --reload
